import datetime
import zoneinfo

example_good_input = "The schedule timezone is US Pacific. The group in the US Pacific timezone will start their rotation on Monday April 29, 2024 at 9am Pacific. The group contains four users: EW, MP, GW, and RG. The group works the following shifts: Monday from 9am-3pm Pacific, Tuesday from 9am-3pm Pacific, and Wednesday from 9am-3pm Pacific. The group will rotate these shifts in the following order: EW, MP, RG, and then GW. The group in the US New York timezone will start their rotation on Monday April 29, 2024 at 3pm Eastern. The group contains 3 users: PB, DS, and BV. This group works the following shifts, in Eastern time: Monday 3-8pm, Tuesday 3-8pm, Wednesday 3-8pm. The rotation order is: PB, DS, DS, BV."

example_good_response = {'timezone': 'America/Los_Angeles',
 'schedule_layers': [{'start': datetime.datetime(2024, 4, 29, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles')),
   'rotation_virtual_start': datetime.datetime(2024, 4, 29, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles')),
   'end': None,
   'rotation_turn_length_seconds': 86400,
   'users': [{'user_initials': 'EW', 'type': 'user_reference'},
    {'user_initials': 'MP', 'type': 'user_reference'},
    {'user_initials': 'RG', 'type': 'user_reference'},
    {'user_initials': 'GW', 'type': 'user_reference'}],
   'restrictions': [{'type': 'daily_restriction',
     'duration_seconds': 18000,
     'start_time_of_day': '09:00:00',
     'start_day_of_week': 1,
     'start_dt': datetime.datetime(2024, 4, 29, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))},
    {'type': 'daily_restriction',
     'duration_seconds': 18000,
     'start_time_of_day': '09:00:00',
     'start_day_of_week': 2,
     'start_dt': datetime.datetime(2024, 4, 30, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))},
    {'type': 'daily_restriction',
     'duration_seconds': 18000,
     'start_time_of_day': '09:00:00',
     'start_day_of_week': 3,
     'start_dt': datetime.datetime(2024, 5, 1, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))}]},
  {'start': datetime.datetime(2024, 4, 29, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles')),
   'rotation_virtual_start': datetime.datetime(2024, 4, 29, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles')),
   'end': None,
   'rotation_turn_length_seconds': 86400,
   'users': [{'user_initials': 'PB', 'type': 'user_reference'},
    {'user_initials': 'DS', 'type': 'user_reference'},
    {'user_initials': 'DS', 'type': 'user_reference'},
    {'user_initials': 'BV', 'type': 'user_reference'}],
   'restrictions': [{'type': 'daily_restriction',
     'duration_seconds': 18000,
     'start_time_of_day': '12:00:00',
     'start_day_of_week': 1,
     'start_dt': datetime.datetime(2024, 4, 29, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))},
    {'type': 'daily_restriction',
     'duration_seconds': 18000,
     'start_time_of_day': '12:00:00',
     'start_day_of_week': 2,
     'start_dt': datetime.datetime(2024, 4, 30, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))},
    {'type': 'daily_restriction',
     'duration_seconds': 18000,
     'start_time_of_day': '12:00:00',
     'start_day_of_week': 3,
     'start_dt': datetime.datetime(2024, 5, 1, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='America/Los_Angeles'))}]}]}